source 'https://cdn.cocoapods.org'

target 'iosApp' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'kmp_webrtc', :path => '../../kmp-webrtc/kmp_webrtc.podspec'
  pod 'WebRTC', :path => '../../libs/apple/WebRTC.podspec'
  pod 'kmp_xlog', '~> 1.3.4'
end
